%% monthy hall
prize    = floor(rand(1,N)*3)+1;
choice   = floor(rand(1,N)*3)+1;
opendoor = ...
    [prize==choice].*(mod(floor(rand(1,N)*2)+prize,3)+1) + ...
    [prize~=choice].*( ...
        [prize==1].*[5-choice] + ...
        [prize==2].*[4-choice] + ...
        [prize==3].*[3-choice] );
switchchoice = ...
    [opendoor==1].*[5-choice] + ...
    [opendoor==2].*[4-choice] + ...
    [opendoor==3].*[3-choice] ;

sum(switchchoice==prize)/N
