function [] = meeg_menu( varargin )
%SOURCES_MENU - Add a MEEG Source related menue
return

[hp,ha,hf]=findTessellationHandles(varargin{:});
uhp=get(hp, 'UserData');

% Remove previous instances
t0=findobj(hf, 'Type', 'uimenu', 'Label', 'MEEG');
delete(t0);

t0=uimenu('Label', 'MEEG', 'Parent', hf)
t1 = uimenu('Parent',t0,...
	'Label','Surface processing');

cback='uhp=get(findTessellationHandles, ''UserData'');';
t11 = uimenu('Parent',t1,...
	'Label','Smooth surface ',...
	'CallBack',[ ...
        'uhp=get(findTessellationHandles, ''UserData'');'...
        'p=handle2struct(uhp.h);p=lowerfields(p.properties);'...
        '[fv]=smooth_cortex(p,uhp.vertconn,.3,10);' ...
        'set(uhp.h, ''Vertices'', fv.vertices)']);
t12 = uimenu('Parent',t1,...
	'Label','Adv. Smooth surface',...
	'CallBack',[ ...
        'uhp=get(findTessellationHandles, ''UserData'');'...
        'p=handle2struct(uhp.h);p=lowerfields(p.properties);'...
        'vals=inputdlg({''Smoothing factor'',''Iterations''}, ''Smooting parameters'', 1 , {''.3'', ''10''});'...
        '[fv]=smooth_cortex(p,uhp.vertconn,str2num(vals{1}),str2num(vals{2}));' ...
        'set(uhp.h, ''Vertices'', fv.vertices)']);
if ~isfield(uhp, 'vertconn')
    set([t11 t12], 'Enable', 'off')
end


t2 = uimenu('Parent',t1,...
	'Label','Back to original surface',...
	'CallBack',[ ...
        'uhp=get(findTessellationHandles, ''UserData'');'...
        'set(uhp.h, ''Vertices'', uhp.vertices)']);

t2 = uimenu('Parent',t1,...
	'Label','Vertex Connectivity',...
	'CallBack','disp(''smoothing'');');

return
% Context menu
t0 = uicontextmenu('Visible', 'on');
cback= ['u=get(gcbf, ''UserData'');' ...
        '[p v vi f fi]=select3d(gcbo);'...
        'figure(''Name'', sprintf(''Scout: Vert#%d [%0.2g %0.2g %0.2g]'', vi, v)); plot(u.time, u.cdata(vi,:));'...
        'hold on; stem(get(u.htime, ''Value''), u.cdata(vi,get(u.htime, ''Value'')), ''.r'')'];

t1 = uimenu('Parent',t0,'Position',1,...
            'Label', 'Scout', 'CallBack', cback);

       

[cortex_smoothed]=smooth_cortex(cortex,cortex.vertconn,.3,10);