function [hmenu]= meegui_menu(action, varargin)
% cortex_menu - Menu related to cortical surface processing

if nargin==0
    action='create';
end
switch lower(action)
    case 'create'
        hmenu=action_create(varargin);
end
return


function [hmenu]=action_create(varargin)
hmenu = uimenu('Label','MEEG Gui');        
cback='uhp=get(findTessellationHandles, ''UserData'');if isempty(uhp); return; end;';
t = uimenu('Parent',hmenu,...
    'Label','Display GUIs',...
    'Checked', 'on',...
    'CallBack', [...
        'if isempty(get(gcbo, ''UserData'')),'...       
        'set(gcbo, ''UserData'', findobj(gcbf, ''type'', ''uicontrol''));'...
        'set(findobj(gcbf, ''type'', ''uicontrol''), ''Visible'', ''off'');'...
        'set(gcbo, ''Checked'', ''off'');'...
    'else,'...
        'set(get(gcbo, ''UserData''), ''Visible'', ''on'');'...
        'set(gcbo, ''UserData'', []);'...
        'set(gcbo, ''Checked'', ''on'');'...
    'end;']);

t = uimenu('Parent',hmenu,...
    'Label','Rotate 3D axes',...
    'Checked', 'off',...
    'CallBack', [...
    'rotate3daxes(get(findTessellationHandles, ''Parent''));'...
    'set(gcbo, ''Checked'',get(findall(gcbf,''Tag'',''figToolRotate3DAxes''),''State''));'...
    ]);


